name: Release

on:
  release:
    types: [published]

jobs:
  tag:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: php-actions/composer@v2
      id: composer
    - name: Commit lib folder (but don't push)
      run: |
        git config --global user.email "dev+codebot@ownerreservations.com" &&
        git config --global user.name "Codebot on GitHub" &&
        sed -i 's/lib/ /' .gitignore &&
        git add .gitignore &&
        git add -f ownerrez/lib . &&
        git commit -m "Dependencies"
    - name: WordPress Plugin Deploy
      id: deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      with:
        generate-zip: true
      env:
        BUILD_DIR: ownerrez
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: ownerrez
    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:        
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ steps.deploy.outputs.zip-path }}
        asset_name: ownerrez.zip
