name: Release

on:
  push:
    tags:
    - "*"

jobs:
  tag:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install dependencies
      uses: php-actions/composer@v2
      id: composer
      with:
        dev: no
    - name: WordPress Plugin Deploy
      uses: Lewiscowles1986/action-wordpress-plugin-deploy@feat/add-custom-workspace
      env:
        WORKSPACE_DIR: ownerrez
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: ownerrez
